services:
  zeppelin:
    image: apache/zeppelin:0.9.0
    container_name: zeppelin
    ports:
      - "8082:8080"
    volumes:
      - ./spark-app:/opt/spark-app
    networks:
      - spark-network-tools

  jupyter:
    image: jupyter/all-spark-notebook:latest
    container_name: jupyter
    ports:
      - "8888:8888"
    volumes:
      - ./spark-app:/opt/spark-app
    networks:
      - spark-network-tools

networks:
  spark-network-tools:
    external: true
