services:
  spark-master-ewma:
    image: custom-spark:latest
    container_name: spark-master-ewma
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_HOST=spark-master-ewma
    ports:
      - "7078:7077"
      - "8081:8080"
    volumes:
      - ./spark-app:/opt/spark-app
    networks:
      - spark-network-ewma

  spark-worker-1-ewma:
    image: custom-spark:latest
    container_name: spark-worker-1-ewma
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master-ewma:7077
    volumes:
      - ./spark-app:/opt/spark-app
    networks:
      - spark-network-ewma

  spark-worker-2-ewma:
    image: custom-spark:latest
    container_name: spark-worker-2-ewma
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master-ewma:7077
    volumes:
      - ./spark-app:/opt/spark-app
    networks:
      - spark-network-ewma

  spark-worker-3-ewma:
    image: custom-spark:latest
    container_name: spark-worker-3-ewma
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master-ewma:7077
    volumes:
      - ./spark-app:/opt/spark-app
    networks:
      - spark-network-ewma

networks:
  spark-network-ewma:
    external: true
